In [1]:
!pip -q install gdown

In [20]:
import pandas as pd

RAW_FILE = "/kaggle/input/datasets/eyaaamhamdi/dataset-tsmc/dataset_TSMC2014_NYC.txt"

df = pd.read_csv(
    RAW_FILE,
    sep="\t",
    header=None,
    encoding="latin1"
)

# Assign the known TSMC2014 columns
df.columns = [
    "user_id",
    "venue_id",
    "venue_category_id",
    "venue_category_name",
    "latitude",
    "longitude",
    "timezone_offset",
    "timestamp"
]

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

display(df.head())

Shape: (227428, 8)

Columns:
['user_id', 'venue_id', 'venue_category_id', 'venue_category_name', 'latitude', 'longitude', 'timezone_offset', 'timestamp']

,user_id,venue_id,venue_category_id,venue_category_name,latitude,longitude,timezone_offset,timestamp
0,470,49bbd6c0f964a520f4531fe3,4bf58dd8d48988d127951735,Arts & Crafts Store,40.719810,-74.002581,-240,Tue Apr 03 18:00:09 +0000 2012
1,979,4a43c0aef964a520c6a61fe3,4bf58dd8d48988d1df941735,Bridge,40.606800,-74.044170,-240,Tue Apr 03 18:00:25 +0000 2012
2,69,4c5cc7b485a1e21e00d35711,4bf58dd8d48988d103941735,Home (private),40.716162,-73.883070,-240,Tue Apr 03 18:02:24 +0000 2012
3,395,4bc7086715a7ef3bef9878da,4bf58dd8d48988d104941735,Medical Center,40.745164,-73.982519,-240,Tue Apr 03 18:02:41 +0000 2012
4,87,4cf2c5321d18a143951b5cec,4bf58dd8d48988d1cb941735,Food Truck,40.740104,-73.989658,-240,Tue Apr 03 18:03:00 +0000 2012

In [21]:
lat_min = df["latitude"].min()
lat_max = df["latitude"].max()

lon_min = df["longitude"].min()
lon_max = df["longitude"].max()

print("TSMC2014 NYC coordinate range")
print("==============================")
print(f"Latitude :  {lat_min} → {lat_max}")
print(f"Longitude: {lon_min} → {lon_max}")

print("\nBounding box:")
print(f"MIN_LAT = {lat_min}")
print(f"MAX_LAT = {lat_max}")
print(f"MIN_LON = {lon_min}")
print(f"MAX_LON = {lon_max}")

TSMC2014 NYC coordinate range
==============================
Latitude :  40.55085246740427 → 40.9883317192653
Longitude: -74.27476644515991 → -73.68382519820906

Bounding box:
MIN_LAT = 40.55085246740427
MAX_LAT = 40.9883317192653
MIN_LON = -74.27476644515991
MAX_LON = -73.68382519820906

In [2]:
import os
import gdown

FILE_ID = "1PNk3zY8NjLcDiAbzjABzY5FiPAFHq6T8"
ZIP_PATH = "/kaggle/working/lsbn2vec_global.zip"

if not os.path.exists(ZIP_PATH):
    gdown.download(
        id=FILE_ID,
        output=ZIP_PATH,
        quiet=False
    )
else:
    print("ZIP already exists:", ZIP_PATH)

print("Size:",
      round(os.path.getsize(ZIP_PATH) / (1024**3), 2),
      "GB")

Downloading...
From (original): https://drive.google.com/uc?id=1PNk3zY8NjLcDiAbzjABzY5FiPAFHq6T8
From (redirected): https://drive.google.com/uc?id=1PNk3zY8NjLcDiAbzjABzY5FiPAFHq6T8&confirm=t&uuid=31995547-bbf8-4907-a765-b0cca593493f
To: /kaggle/working/lsbn2vec_global.zip
100%|██████████| 2.68G/2.68G [00:36<00:00, 72.6MB/s]

Size: 2.5 GB

In [3]:
import zipfile
import os

ZIP_PATH = "/kaggle/working/lsbn2vec_global.zip"

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    files = z.infolist()

print("Number of files:", len(files))

for f in files:
    print(
        f.filename,
        "| compressed:",
        round(f.compress_size / 1024**2, 2), "MB",
        "| uncompressed:",
        round(f.file_size / 1024**2, 2), "MB"
    )

Number of files: 10
dataset_WWW2019/ | compressed: 0.0 MB | uncompressed: 0.0 MB
dataset_WWW2019/raw_Checkins_anonymized.txt | compressed: 1838.1 MB | uncompressed: 5826.98 MB
__MACOSX/dataset_WWW2019/._raw_Checkins_anonymized.txt | compressed: 0.0 MB | uncompressed: 0.0 MB
dataset_WWW2019/raw_POIs.txt | compressed: 249.55 MB | uncompressed: 672.12 MB
__MACOSX/dataset_WWW2019/._raw_POIs.txt | compressed: 0.0 MB | uncompressed: 0.0 MB
dataset_WWW2019/dataset_WWW_friendship_old.txt | compressed: 1.67 MB | uncompressed: 4.92 MB
dataset_WWW2019/dataset_WWW_readme.txt | compressed: 0.0 MB | uncompressed: 0.0 MB
__MACOSX/dataset_WWW2019/._dataset_WWW_readme.txt | compressed: 0.0 MB | uncompressed: 0.0 MB
dataset_WWW2019/dataset_WWW_Checkins_anonymized.txt | compressed: 467.62 MB | uncompressed: 1471.92 MB
dataset_WWW2019/dataset_WWW_friendship_new.txt | compressed: 2.72 MB | uncompressed: 8.34 MB

In [4]:
with zipfile.ZipFile(ZIP_PATH, "r") as z:
    readme_files = [
        f for f in z.namelist()
        if "readme" in f.lower()
    ]

print(readme_files)

['dataset_WWW2019/dataset_WWW_readme.txt', '__MACOSX/dataset_WWW2019/._dataset_WWW_readme.txt']

In [5]:
with zipfile.ZipFile(ZIP_PATH, "r") as z:
    for filename in readme_files:
        print("\n" + "="*80)
        print(filename)
        print("="*80)
        print(z.read(filename).decode("utf-8", errors="replace"))

================================================================================
dataset_WWW2019/dataset_WWW_readme.txt
================================================================================
This dataset includes long-term (about 22 months from Apr. 2012 to Jan. 2014) global-scale check-in data collected from Foursquare, and also two snapshots of user social networks before and after the check-in data collection period (see more details in our paper).


The check-in dataset contains 22,809,624 checkins by 114,324 users on 3,820,891 venues. The social network data contains 363,704 (old) and 607,333 (new) friendships.

- File dataset_WWW_Checkins_anonymized.txt contains check-ins with 4 columns, which are:
1. User ID (anonymized)
2. Venue ID (Foursquare, more information see below in raw_POIs.txt)
3. UTC time
4. Timezone offset in minutes (The offset in minutes between when this check-sin occurred and the same time in UTC, i.e., UTC time + offset is the local time)

- File dataset_WWW_friendship_old.txt and dataset_WWW_friendship_old.txt contains 2 columns. Each row indicating a friendship between two users.



We also publish the raw check-in dataset containing 90,048,627 checkins by 2,733,324 users on 11,180,160 venues. It contains two files in tsv format.

- File raw_Checkins_anonymized.txt has the same format as raw_checkins_anonymized.txt

- File raw_POIs.txt contains all venue data with 5 columns, which are:
1. Venue ID (Foursquare)
2. Latitude
3. Longitude
4. Venue category name (Foursquare)
5. Country code (ISO 3166-1 alpha-2 two-letter country codes)



=============================================================================================================================
Please cite our papers if you publish material based on this dataset.

- Dingqi Yang, Bingqing Qu, Jie Yang, Philippe Cudre-Mauroux, "Revisiting User Mobility and Social Relationships in LBSNs: A Hypergraph Embedding Approach." In WWW'19.

=============================================================================================================================


================================================================================
__MACOSX/dataset_WWW2019/._dataset_WWW_readme.txt
================================================================================
    Mac OS X            	   2   ~      �                                      ATTR       �   �                     �     com.apple.lastuseddate#PS    ��@d    �a"-    

inspect raw_POIs.txt

In [31]:
import zipfile
import pandas as pd

ZIP_PATH = "/kaggle/working/lsbn2vec_global.zip"

POI_FILE = "dataset_WWW2019/raw_POIs.txt"

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    with z.open(POI_FILE) as f:
        poi_sample = pd.read_csv(
            f,
            sep="\t",
            header=None,
        )

display(poi_sample)
print("Shape:", poi_sample.shape)

,0,1,2,3,4
0,3fd66200f964a52000e61ee3,40.729209,-73.998753,Post Office,US
1,3fd66200f964a52000e71ee3,40.733596,-74.003139,Jazz Club,US
2,3fd66200f964a52000e81ee3,40.758102,-73.975734,Gym,US
3,3fd66200f964a52000ea1ee3,40.732456,-74.003755,Indian Restaurant,US
4,3fd66200f964a52000ec1ee3,42.345907,-71.087001,Indian Restaurant,US
...,...,...,...,...,...
11180155,52e92ec0498e1a09484475c9,55.852631,37.447034,Residential Building (Apartment / Condo),RU
11180156,52e92f11498e8e25136e9fe2,-4.329570,-40.711533,Dentist's Office,BR
11180157,52e92f4511d2a77832a49eec,52.505471,13.368507,Financial or Legal Service,DE
11180158,52e92fa5498ef926067570ff,41.025367,28.554854,City,TR
11180159,52e92fcb498ebb8d7cf88323,16.496388,102.822726,Home (private),TH

Shape: (11180160, 5)

In [32]:
poi_sample[4].unique()

array(['US', 'AT', 'DE', 'NL', 'FR', 'SG', 'GB', 'CA', 'BE', 'DK', 'HK',
       'GR', 'GT', 'IT', 'AU', 'ES', 'BM', 'JP', 'IE', 'SE', 'PR', 'NO',
       'AR', 'IN', 'CN', 'EE', 'TR', 'CZ', 'CH', 'VA', 'FI', 'TW', 'AE',
       'PT', 'ZA', 'PS', 'MX', 'SK', 'RU', 'QA', 'TH', 'CL', 'MA', 'MC',
       'HU', 'IL', 'SI', 'BR', 'NZ', 'KR', 'MY', 'ID', 'IS', 'VN', 'MP',
       'EG', 'BS', 'JO', 'MQ', 'CO', 'TC', 'CY', 'RO', 'MO', 'UY', 'PL',
       'HR', nan, 'KE', 'EC', 'PH', 'BB', 'VI', 'UA', 'PA', 'CR', 'VG',
       'KY', 'VC', 'SA', 'LK', 'GE', 'VE', 'LU', 'DO', 'HN', 'IM', 'GU',
       'PY', 'PE', 'LT', 'RS', 'XX', 'GG', 'KW', 'GP', 'AW', 'BY', 'HT',
       'TT', 'AM', 'LV', 'BG', 'NG', 'BH', 'JM', 'MT', 'ME', 'LC', 'MK',
       'LA', 'TN', 'PK', 'KH', 'LB', 'BD', 'NC', 'GH', 'GL', 'AD', 'JE',
       'OM', 'BL', 'SV', 'AN', 'MV', 'BO', 'GI', 'NI', 'NP', 'AO', 'BN',
       'SY', 'TD', 'SD', 'ET', 'TZ', 'KN', 'AL', 'CD', 'IC', 'MU', 'SR',
       'MZ', 'BZ', 'GD', 'MM', 'AF', 'ML', 'MF', 'FJ', 'DZ', 'BA', 'LI',
       'DM', 'UG', 'KP', 'KZ', 'XK', 'SN', 'AG', 'BW', 'IQ', 'PG', 'AZ',
       'ZM', 'KG', 'FO', 'GF', 'IR', 'DJ', 'UZ', 'WS', 'AS', 'CI', 'SJ',
       'MD', 'SC', 'TJ', 'RW', 'PW', 'MN', 'CU', 'AI', 'MW', 'CW', 'KI',
       'SM', 'BT', 'SX', 'PF', 'AX', 'BJ', 'CM', 'GA', 'MG', 'YE', 'VU',
       'TO', 'LY', 'CK', 'ZW', 'SZ', 'RE', 'BF', 'BI', 'GQ', 'CV', 'NE',
       'GM', 'GY', 'FK', 'AQ', 'LR', 'TL', 'ST', 'TG', 'TM', 'LS', 'CG',
       'SL', 'SO', 'GN', 'EH', 'YT', 'KM', 'MR', 'TV', 'NF', 'MS', 'SB',
       'MH', 'SH', 'CX', 'UM', 'PM', 'TA', 'CS', 'EU', 'CP', 'JT', 'BV',
       'FM', 'NT', 'DD', 'BQ', 'NU', 'TF', 'FX', 'CF', 'ER', 'WF', 'NR',
       'GS'], dtype=object)

In [10]:
poi_columns = [
    "venue_id",
    "latitude",
    "longitude",
    "category",
    "country_code"
]

poi_sample.columns = poi_columns

display(poi_sample)

,venue_id,latitude,longitude,category,country_code
0,3fd66200f964a52000e61ee3,40.729209,-73.998753,Post Office,US
1,3fd66200f964a52000e71ee3,40.733596,-74.003139,Jazz Club,US
2,3fd66200f964a52000e81ee3,40.758102,-73.975734,Gym,US
3,3fd66200f964a52000ea1ee3,40.732456,-74.003755,Indian Restaurant,US
4,3fd66200f964a52000ec1ee3,42.345907,-71.087001,Indian Restaurant,US
5,3fd66200f964a52000ee1ee3,39.933178,-75.159262,Sandwich Place,US
6,3fd66200f964a52000ef1ee3,34.188944,-118.320329,Karaoke Bar,US
7,3fd66200f964a52000f01ee3,34.010279,-118.495523,Beer Garden,US
8,3fd66200f964a52000f11ee3,40.652766,-74.003092,Bowling Alley,US
9,3fd66200f964a52001e51ee3,40.726961,-73.980039,Dive Bar,US

# find NYC POIs

We used the geographical coordinates.

In [22]:
NYC_LAT_MIN = lat_min
NYC_LAT_MAX = lat_max

NYC_LON_MIN = lon_min
NYC_LON_MAX = lon_max

In [23]:
NYC_POI_FILE = "/kaggle/working/nyc_pois.tsv"

first_chunk = True
total_nyc_pois = 0

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    with z.open(POI_FILE) as f:

        for chunk in pd.read_csv(
            f,
            sep="\t",
            header=None,
            names=poi_columns,
            chunksize=500_000
        ):

            # Make sure coordinates are numeric
            chunk["latitude"] = pd.to_numeric(
                chunk["latitude"],
                errors="coerce"
            )

            chunk["longitude"] = pd.to_numeric(
                chunk["longitude"],
                errors="coerce"
            )

            mask = (
                chunk["latitude"].between(
                    NYC_LAT_MIN,
                    NYC_LAT_MAX
                )
                &
                chunk["longitude"].between(
                    NYC_LON_MIN,
                    NYC_LON_MAX
                )
            )

            nyc_chunk = chunk.loc[mask]

            if len(nyc_chunk) > 0:
                nyc_chunk.to_csv(
                    NYC_POI_FILE,
                    sep="\t",
                    index=False,
                    mode="w" if first_chunk else "a",
                    header=first_chunk
                )

                first_chunk = False
                total_nyc_pois += len(nyc_chunk)

print("NYC POIs:", total_nyc_pois)

NYC POIs: 105728

In [24]:
nyc_pois = pd.read_csv(
    NYC_POI_FILE,
    sep="\t"
)

print("NYC POIs:", len(nyc_pois))
print("Unique venues:", nyc_pois["venue_id"].nunique())

display(nyc_pois.head())

NYC POIs: 105728
Unique venues: 105728

,venue_id,latitude,longitude,category,country_code
0,3fd66200f964a52000e61ee3,40.729209,-73.998753,Post Office,US
1,3fd66200f964a52000e71ee3,40.733596,-74.003139,Jazz Club,US
2,3fd66200f964a52000e81ee3,40.758102,-73.975734,Gym,US
3,3fd66200f964a52000ea1ee3,40.732456,-74.003755,Indian Restaurant,US
4,3fd66200f964a52000f11ee3,40.652766,-74.003092,Bowling Alley,US

In [25]:
nyc_venue_ids = set(
    nyc_pois["venue_id"].astype(str)
)

len(nyc_venue_ids)

105728

In [26]:
CHECKIN_FILE = (
    "dataset_WWW2019/"
    "dataset_WWW_Checkins_anonymized.txt"
)

NYC_CHECKIN_FILE = (
    "/kaggle/working/"
    "nyc_checkins.tsv"
)

checkin_columns = [
    "user_id",
    "venue_id",
    "utc_time",
    "timezone_offset"
]

first_chunk = True
total_nyc_checkins = 0

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    with z.open(CHECKIN_FILE) as f:

        for i, chunk in enumerate(
            pd.read_csv(
                f,
                sep="\t",
                header=None,
                names=checkin_columns,
                chunksize=500_000,
                dtype={
                    "user_id": str,
                    "venue_id": str
                }
            )
        ):

            mask = chunk["venue_id"].isin(nyc_venue_ids)

            nyc_chunk = chunk.loc[mask]

            if len(nyc_chunk) > 0:

                nyc_chunk.to_csv(
                    NYC_CHECKIN_FILE,
                    sep="\t",
                    index=False,
                    mode="w" if first_chunk else "a",
                    header=first_chunk
                )

                first_chunk = False
                total_nyc_checkins += len(nyc_chunk)

            if i % 10 == 0:
                print(
                    f"Processed chunk {i:,} | "
                    f"NYC check-ins: {total_nyc_checkins:,}"
                )

print(
    "TOTAL NYC CHECK-INS:",
    total_nyc_checkins
)

Processed chunk 0 | NYC check-ins: 7,670
Processed chunk 10 | NYC check-ins: 79,856
Processed chunk 20 | NYC check-ins: 142,418
Processed chunk 30 | NYC check-ins: 201,530
Processed chunk 40 | NYC check-ins: 262,482
TOTAL NYC CHECK-INS: 292353

In [33]:
import os
import zipfile
import multiprocessing as mp

import pandas as pd
import numpy as np

# ============================================================
# CONFIG
# ============================================================

DATASET = "NYC"

ZIP_PATH = "/kaggle/working/lsbn2vec_global.zip"

OUTPUT_DIR = "/kaggle/working"

# Dataset #5 files
POI_FILE = "dataset_WWW2019/raw_POIs.txt"

CHECKIN_FILE = (
    "dataset_WWW2019/"
    "dataset_WWW_Checkins_anonymized.txt"
)

FRIENDSHIP_OLD_FILE = (
    "dataset_WWW2019/"
    "dataset_WWW_friendship_old.txt"
)

FRIENDSHIP_NEW_FILE = (
    "dataset_WWW2019/"
    "dataset_WWW_friendship_new.txt"
)

# ============================================================
# Same filtering as your previous TSMC notebook
# ============================================================

MIN_VENUE_VISITS = 10
MIN_USER_VISITS = 30

# ============================================================
# NYC geographic bounds
# ============================================================

NYC_LAT_MIN = 40.49
NYC_LAT_MAX = 40.92

NYC_LON_MIN = -74.27
NYC_LON_MAX = -73.65

# ============================================================
# Chunk sizes
# ============================================================

POI_CHUNKSIZE = 500_000
CHECKIN_CHUNKSIZE = 500_000
FRIENDSHIP_CHUNKSIZE = 500_000

os.makedirs(OUTPUT_DIR, exist_ok=True)

print("Configuration ready.")

Configuration ready.

In [34]:
poi_columns = [
    "venue_id",
    "latitude",
    "longitude",
    "venue_category_name",
    "country_code",
]

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    with z.open(POI_FILE) as f:
        poi_sample = pd.read_csv(
            f,
            sep="\t",
            header=None,
            names=poi_columns,
            nrows=10
        )

display(poi_sample)

,venue_id,latitude,longitude,venue_category_name,country_code
0,3fd66200f964a52000e61ee3,40.729209,-73.998753,Post Office,US
1,3fd66200f964a52000e71ee3,40.733596,-74.003139,Jazz Club,US
2,3fd66200f964a52000e81ee3,40.758102,-73.975734,Gym,US
3,3fd66200f964a52000ea1ee3,40.732456,-74.003755,Indian Restaurant,US
4,3fd66200f964a52000ec1ee3,42.345907,-71.087001,Indian Restaurant,US
5,3fd66200f964a52000ee1ee3,39.933178,-75.159262,Sandwich Place,US
6,3fd66200f964a52000ef1ee3,34.188944,-118.320329,Karaoke Bar,US
7,3fd66200f964a52000f01ee3,34.010279,-118.495523,Beer Garden,US
8,3fd66200f964a52000f11ee3,40.652766,-74.003092,Bowling Alley,US
9,3fd66200f964a52001e51ee3,40.726961,-73.980039,Dive Bar,US

In [35]:
NYC_POI_FILE = os.path.join(
    OUTPUT_DIR,
    "nyc_pois_all.tsv"
)

first_chunk = True
total_nyc_pois = 0

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    with z.open(POI_FILE) as f:

        for i, chunk in enumerate(
            pd.read_csv(
                f,
                sep="\t",
                header=None,
                names=poi_columns,
                chunksize=POI_CHUNKSIZE,
                dtype={
                    "venue_id": str,
                    "country_code": str,
                }
            )
        ):

            chunk["latitude"] = pd.to_numeric(
                chunk["latitude"],
                errors="coerce"
            )

            chunk["longitude"] = pd.to_numeric(
                chunk["longitude"],
                errors="coerce"
            )

            mask = (
                chunk["latitude"].between(
                    NYC_LAT_MIN,
                    NYC_LAT_MAX
                )
                &
                chunk["longitude"].between(
                    NYC_LON_MIN,
                    NYC_LON_MAX
                )
            )

            nyc_chunk = chunk.loc[mask]

            if len(nyc_chunk):

                nyc_chunk.to_csv(
                    NYC_POI_FILE,
                    sep="\t",
                    index=False,
                    mode="w" if first_chunk else "a",
                    header=first_chunk
                )

                first_chunk = False
                total_nyc_pois += len(nyc_chunk)

            if i % 10 == 0:
                print(
                    f"Processed POI chunk {i:,} | "
                    f"NYC POIs: {total_nyc_pois:,}"
                )

print()
print("Initial NYC geographic POIs:", total_nyc_pois)

Processed POI chunk 0 | NYC POIs: 19,796
Processed POI chunk 10 | NYC POIs: 74,361
Processed POI chunk 20 | NYC POIs: 99,886

Initial NYC geographic POIs: 102687

In [36]:
nyc_pois = pd.read_csv(
    NYC_POI_FILE,
    sep="\t",
    dtype={"venue_id": str}
)

nyc_venue_ids = set(
    nyc_pois["venue_id"]
)

print(
    f"Geographic NYC POIs: "
    f"{len(nyc_venue_ids):,}"
)

Geographic NYC POIs: 102,687

In [37]:
NYC_RAW_CHECKINS = os.path.join(
    OUTPUT_DIR,
    "nyc_checkins_raw.tsv"
)

checkin_columns = [
    "user_id",
    "venue_id",
    "utc_time",
    "timezone_offset",
]

first_chunk = True
total_nyc_checkins = 0

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    with z.open(CHECKIN_FILE) as f:

        for i, chunk in enumerate(
            pd.read_csv(
                f,
                sep="\t",
                header=None,
                names=checkin_columns,
                chunksize=CHECKIN_CHUNKSIZE,
                dtype={
                    "user_id": str,
                    "venue_id": str,
                }
            )
        ):

            mask = chunk["venue_id"].isin(
                nyc_venue_ids
            )

            nyc_chunk = chunk.loc[mask]

            if len(nyc_chunk):

                nyc_chunk.to_csv(
                    NYC_RAW_CHECKINS,
                    sep="\t",
                    index=False,
                    mode="w" if first_chunk else "a",
                    header=first_chunk
                )

                first_chunk = False
                total_nyc_checkins += len(nyc_chunk)

            if i % 10 == 0:
                print(
                    f"Processed check-in chunk {i:,} | "
                    f"NYC check-ins: {total_nyc_checkins:,}"
                )

print()
print(
    f"Initial NYC check-ins: "
    f"{total_nyc_checkins:,}"
)

Processed check-in chunk 0 | NYC check-ins: 7,495
Processed check-in chunk 10 | NYC check-ins: 78,451
Processed check-in chunk 20 | NYC check-ins: 140,304
Processed check-in chunk 30 | NYC check-ins: 198,629
Processed check-in chunk 40 | NYC check-ins: 258,668

Initial NYC check-ins: 288,188

In [38]:
NYC_RAW_CHECKINS = os.path.join(
    OUTPUT_DIR,
    "nyc_checkins_raw.tsv"
)

checkin_columns = [
    "user_id",
    "venue_id",
    "utc_time",
    "timezone_offset",
]

first_chunk = True
total_nyc_checkins = 0

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    with z.open(CHECKIN_FILE) as f:

        for i, chunk in enumerate(
            pd.read_csv(
                f,
                sep="\t",
                header=None,
                names=checkin_columns,
                chunksize=CHECKIN_CHUNKSIZE,
                dtype={
                    "user_id": str,
                    "venue_id": str,
                }
            )
        ):

            mask = chunk["venue_id"].isin(
                nyc_venue_ids
            )

            nyc_chunk = chunk.loc[mask]

            if len(nyc_chunk):

                nyc_chunk.to_csv(
                    NYC_RAW_CHECKINS,
                    sep="\t",
                    index=False,
                    mode="w" if first_chunk else "a",
                    header=first_chunk
                )

                first_chunk = False
                total_nyc_checkins += len(nyc_chunk)

            if i % 10 == 0:
                print(
                    f"Processed check-in chunk {i:,} | "
                    f"NYC check-ins: {total_nyc_checkins:,}"
                )

print()
print(
    f"Initial NYC check-ins: "
    f"{total_nyc_checkins:,}"
)

Processed check-in chunk 0 | NYC check-ins: 7,495
Processed check-in chunk 10 | NYC check-ins: 78,451
Processed check-in chunk 20 | NYC check-ins: 140,304
Processed check-in chunk 30 | NYC check-ins: 198,629
Processed check-in chunk 40 | NYC check-ins: 258,668

Initial NYC check-ins: 288,188

In [39]:
df = pd.read_csv(
    NYC_RAW_CHECKINS,
    sep="\t",
    dtype={
        "user_id": str,
        "venue_id": str,
    }
)

print(f"Raw NYC rows     : {len(df):,}")
print(f"Unique NYC users : {df['user_id'].nunique():,}")
print(f"Unique NYC venues: {df['venue_id'].nunique():,}")

display(df.head())

Raw NYC rows     : 288,188
Unique NYC users : 9,097
Unique NYC venues: 44,322

,user_id,venue_id,utc_time,timezone_offset
0,163640,4b1d4b75f964a520560e24e3,Tue Apr 03 18:00:52 +0000 2012,-240
1,192373,4a65102bf964a5203bc71fe3,Tue Apr 03 18:02:05 +0000 2012,-240
2,168076,49edce76f964a520f9671fe3,Tue Apr 03 18:02:32 +0000 2012,-240
3,468002,4a8d9afef964a520351020e3,Tue Apr 03 18:02:41 +0000 2012,-240
4,54007,4cf2c5321d18a143951b5cec,Tue Apr 03 18:03:00 +0000 2012,-240

In [40]:
print(df["utc_time"].head(10).tolist())

['Tue Apr 03 18:00:52 +0000 2012', 'Tue Apr 03 18:02:05 +0000 2012', 'Tue Apr 03 18:02:32 +0000 2012', 'Tue Apr 03 18:02:41 +0000 2012', 'Tue Apr 03 18:03:00 +0000 2012', 'Tue Apr 03 18:04:42 +0000 2012', 'Tue Apr 03 18:04:47 +0000 2012', 'Tue Apr 03 18:05:09 +0000 2012', 'Tue Apr 03 18:06:08 +0000 2012', 'Tue Apr 03 18:07:15 +0000 2012']

In [41]:
df["utc_time"] = pd.to_datetime(
    df["utc_time"],
    utc=True,
    errors="coerce"
)

print(
    "Invalid timestamps:",
    df["utc_time"].isna().sum()
)

print(
    "Date range:",
    df["utc_time"].min(),
    "→",
    df["utc_time"].max()
)

/tmp/ipykernel_58/2036367543.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["utc_time"] = pd.to_datetime(

Invalid timestamps: 0
Date range: 2012-04-03 18:00:52+00:00 → 2014-01-29 16:36:56+00:00

In [42]:
venue_counts = df["venue_id"].value_counts()

valid_venues = venue_counts[
    venue_counts >= MIN_VENUE_VISITS
].index

df = df[
    df["venue_id"].isin(valid_venues)
].copy()

print(
    f"After POI filter "
    f"(>= {MIN_VENUE_VISITS} visits):"
)

print(
    f"Rows   : {len(df):,}"
)

print(
    f"Venues : {df['venue_id'].nunique():,}"
)

print(
    f"Users  : {df['user_id'].nunique():,}"
)

After POI filter (>= 10 visits):
Rows   : 197,451
Venues : 6,138
Users  : 8,587

In [43]:
user_counts = df["user_id"].value_counts()

valid_users = user_counts[
    user_counts >= MIN_USER_VISITS
].index

df = df[
    df["user_id"].isin(valid_users)
].copy()

print(
    f"After user filter "
    f"(>= {MIN_USER_VISITS} visits):"
)

print(
    f"Rows   : {len(df):,}"
)

print(
    f"Venues : {df['venue_id'].nunique():,}"
)

print(
    f"Users  : {df['user_id'].nunique():,}"
)

After user filter (>= 30 visits):
Rows   : 159,304
Venues : 6,103
Users  : 1,665

In [45]:
print("=" * 60)
print("OUR NYC DATASET")
print("=" * 60)

print(
    f"Check-ins : {len(df):,}"
)

print(
    f"Users     : {df['user_id'].nunique():,}"
)

print(
    f"POIs      : {df['venue_id'].nunique():,}"
)

============================================================
OUR NYC DATASET
============================================================
Check-ins : 159,304
Users     : 1,665
POIs      : 6,103

In [46]:
final_venue_ids = set(
    df["venue_id"].unique()
)

poi_meta = nyc_pois[
    nyc_pois["venue_id"].isin(
        final_venue_ids
    )
].copy()

print(
    "Final POI metadata:",
    len(poi_meta)
)

print(
    "Final check-in POIs:",
    df["venue_id"].nunique()
)

display(poi_meta.head())

Final POI metadata: 6103
Final check-in POIs: 6103

,venue_id,latitude,longitude,venue_category_name,country_code
1,3fd66200f964a52000e71ee3,40.733596,-74.003139,Jazz Club,US
2,3fd66200f964a52000e81ee3,40.758102,-73.975734,Gym,US
6,3fd66200f964a52001e81ee3,40.756377,-73.967653,Sports Bar,US
11,3fd66200f964a52003e71ee3,40.739685,-74.006020,French Restaurant,US
12,3fd66200f964a52003e81ee3,40.756119,-73.972532,Hotel Bar,US

In [47]:
poi_meta = poi_meta[
    [
        "venue_id",
        "latitude",
        "longitude",
        "venue_category_name",
        "country_code",
    ]
].drop_duplicates(
    subset="venue_id"
)

print(poi_meta.shape)

(6103, 5)

## Load friendship edges and filter to our final active users

We only keep an edge if **both** users survived the POI/user visit filters above (i.e. both are in the final `df`).

In [48]:
final_user_ids = set(df["user_id"].astype(str))
print(f"Final active users: {len(final_user_ids):,}")

Final active users: 1,665

In [49]:
friendship_columns = ["user1", "user2"]

def load_and_filter_friendships(file_in_zip, valid_users):
    total_rows = 0
    total_kept = 0
    frames = []

    with zipfile.ZipFile(ZIP_PATH, "r") as z:
        with z.open(file_in_zip) as f:
            for chunk in pd.read_csv(
                f,
                sep="\t",
                header=None,
                names=friendship_columns,
                chunksize=FRIENDSHIP_CHUNKSIZE,
                dtype={"user1": str, "user2": str},
            ):
                total_rows += len(chunk)

                mask = (
                    chunk["user1"].isin(valid_users)
                    & chunk["user2"].isin(valid_users)
                )

                kept = chunk.loc[mask]

                if len(kept):
                    frames.append(kept)
                    total_kept += len(kept)

    print(file_in_zip)
    print(f"  Edges scanned : {total_rows:,}")
    print(f"  Edges kept (both users in our dataset): {total_kept:,}")

    if frames:
        return pd.concat(frames, ignore_index=True)
    return pd.DataFrame(columns=friendship_columns)

friends_old = load_and_filter_friendships(FRIENDSHIP_OLD_FILE, final_user_ids)
friends_new = load_and_filter_friendships(FRIENDSHIP_NEW_FILE, final_user_ids)

dataset_WWW2019/dataset_WWW_friendship_old.txt
  Edges scanned : 363,704
  Edges kept (both users in our dataset): 1,507
dataset_WWW2019/dataset_WWW_friendship_new.txt
  Edges scanned : 607,333
  Edges kept (both users in our dataset): 2,278

In [50]:
friendships = pd.concat([friends_old, friends_new], ignore_index=True)

# de-duplicate edges (old + new files can overlap)
friendships = friendships.drop_duplicates().reset_index(drop=True)

# drop any self-loops just in case
friendships = friendships[friendships["user1"] != friendships["user2"]].copy()

n_users_in_friendships = pd.unique(friendships[["user1", "user2"]].values.ravel()).shape[0]

print("=" * 60)
print("FILTERED FRIENDSHIPS (only our final users)")
print("=" * 60)
print(f"Edges : {len(friendships):,}")
print(f"Users appearing in an edge: {n_users_in_friendships:,} / {len(final_user_ids):,}")

display(friendships.head())

============================================================
FILTERED FRIENDSHIPS (only our final users)
============================================================
Edges : 2,644
Users appearing in an edge: 1,261 / 1,665

  user1  user2
0    19   1356
1    19   1668
2    19  29643
3    19  39447
4    19  88203

In [51]:
CHECKINS_OUT = os.path.join(OUTPUT_DIR, "nyc_checkins_final.csv")
POIS_OUT = os.path.join(OUTPUT_DIR, "nyc_pois_final.csv")
FRIENDSHIPS_OUT = os.path.join(OUTPUT_DIR, "nyc_friendships_final.csv")

df.to_csv(CHECKINS_OUT, index=False)
poi_meta.to_csv(POIS_OUT, index=False)
friendships.to_csv(FRIENDSHIPS_OUT, index=False)

print("Saved final dataset files:")
print(f"  - {CHECKINS_OUT}     ({len(df):,} rows)")
print(f"  - {POIS_OUT}         ({len(poi_meta):,} rows)")
print(f"  - {FRIENDSHIPS_OUT}  ({len(friendships):,} rows)")

Saved final dataset files:
  - /kaggle/working/nyc_checkins_final.csv     (159,304 rows)
  - /kaggle/working/nyc_pois_final.csv         (6,103 rows)
  - /kaggle/working/nyc_friendships_final.csv  (2,644 rows)